package types

import "fmt"

// WeightedOutputs is to make structs which is using weight to be based on
type WeightedOutputs struct {
	EntryIDs []string
	Weight   string
}

func (ol WeightedOutputs) String() string {
	return fmt.Sprintf("WeightedOutputs{EntryIDs: %v, Weight: %v}", ol.EntryIDs, ol.Weight)
}

// WeightedOutputsList is a struct to keep items which can be generated by weight;
// ItemOutput and CoinOutput is possible in current stage
type WeightedOutputsList []WeightedOutputs

func (wol WeightedOutputsList) String() string {
	itm := "WeightedOutputsList{"

	for _, output := range wol {
		itm += output.String() + ",\n"
	}

	itm += "}"
	return itm
}
